# This file provides instructions for packaging.

`Sub-Infix`
	deps:runtime-requirement [ deps:on "perl 5.006"^^deps:CpanId ];
	deps:test-requirement    [ deps:on "Test::More 0.47"^^deps:CpanId ];
	deps:test-requirement    [ deps:on "Test::Fatal"^^deps:CpanId ].

